require 'rake'
require 'spec/rake/spectask'

task :default => :spec

desc "Verify our specification"
Spec::Rake::SpecTask.new 'spec' => 'bin/admix' do |t|
  t.spec_files = FileList['spec/*_spec.rb']
  t.libs = ["lib"]
end

file 'orig/admix' do
  sh 'cd orig; make'
end

file 'bin/admix' => ['orig/admix','bin'] do
  cp 'orig/admix', 'bin/admix'
end

file 'bin' do
  mkdir 'bin'
end

task :clean do
  sh 'cd orig; make distclean'
  rm 'bin/admix'
end
