--- !ditz.rubyforge.org,2008-03-06/project 
name: admix
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: admix
- !ditz.rubyforge.org,2008-03-06/component 
  name: AdmixWeb
- !ditz.rubyforge.org,2008-03-06/component 
  name: AdmixWrapper
releases: []

