require 'rake'
require 'spec/rake/spectask'

desc "Verify our specification"
Spec::Rake::SpecTask.new 'spec' => 'orig/admix' do |t|
  t.spec_files = FileList['spec/*_spec.rb']
end

file 'orig/admix' do
  cd 'orig'
  sh 'make'
end
